* dot-files repository
All the dot-files for my Arch Linux installation with *i3-gaps* as the tiling window manager.

** configuring the system

+ Configure *ZSH*:
  + Install and use ~zsh~ as the default shell by running ~chsh -s $(which zsh)~.
  + Install ~zimfw~ by following the instructions as defined [[https://github.com/zimfw/zimfw][here]]
  + After installation, run ~zimfw install~ followed by ~zimfw uninstall~, to modify the plugins for ~zimfw~.
  + Install ~alacritty~ as the default terminal.
+ Keyboard configuration:
  + Install ~xorg-xmodmap~ and ~xkbset~ to setup keyboard.
  + Left control is now =hyper= and Caps Lock is now =control= 
  + sticky keys are enabled without locking.
+ Install =redshift= to warn the screen during night times to reduce eye strain
  + Enable ~redshift~  by running ~systemctl --user enable redshift-gtk.service~ and start it by running ~systemctl --user start redshift-gtk.service~
  + In order to allow access Redshift to use GeoClue2, add the following lines to ~/etc/geoclue/geoclue.conf~: 
#+begin_src conf
[redshift]
allowed=true
system=false
users=
#+end_src
+ copy =low-battery-alert.service= and =low-battery-alert.timer= to =/etc/systemd/system/= and enable both of them by running =sudo systemctl enable low-battery-alert.service= and =sudo systemctl enable low-battery-alert.timer=.
+ Configure media
  + Run ~mkdir -p ~/.config/mpd/playlists~ and  enable ~mpd~ service by running: ~sudo systemctl enable mpd.service~
  + Use ~ncmpcpp~ as the client for mpd
  + Install ~mpDris2~ (from AUR) and enable it by running ~systemctl --user enable mpDris2~
  + Install =playerctl= and =pulseaudio-ctl= for media controls
+ Install ~deadd-notification-center~ for getting notifications for  *i3*
+ Install ~rofi~ as the application launcher.
+ Use =unclutter= to hide mouse pointer after a few seconds of idle time.
+ Use =feh= to set the wallpaper background.
+ Use [[https://github.com/yshui/picom/][picom]] as the display compositor for i3. Install from `git`, for Archlinux, install using `picom-git` from AUR.
  + Use experimental backends option when running picom, otherwise the `glx` backend will not work.
+ Use ~udiskie~ to get notifications and manage devices connected to the system.
+ Use =i3lock= as the lockscreen for i3. Install =xss-lock= and =xautolock= for power management during lock.
+ Use =maim= and =xdotool= to take desktop screenshots. =xdotool= is also used to get picture in picture effect using i3.
+ Install =xorg-backlight= brightness of the screen
+ Install =xorg-xinput= for enabling/disabling touchpad
