#!/usr/bin/env bash

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

maim -s | xclip -selection clipboard -t image/png
sleep 1
notify-send 'Screenshot copied to clipboard'
