#!/usr/bin/env bash

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

maim -i $(xdotool getactivewindow) ~/Pictures/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png
sleep 1
notify-send 'Screenshot captured'
