icons = "awesome"

# Nord color scheme
[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#2E3440"
idle_fg = "#E5E9F0"
info_bg = "#B48EAD"
info_fg = "#2E3440"
good_bg = "#5E81AC"
good_fg = "#2E3440"
warning_bg = "#EBCB8B"
warning_fg = "#2E3440"
critical_bg = "#BF616A"
critical_fg = "#2E3440"
# The rest of the theme settings are left at default.

[[block]]
block = "music"
player = "mpd"

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
signal_strength = true
ip = true
interval = 5
use_bits = false
speed_up = false
speed_down = false

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "cpu"
interval = 1
format = "{utilization}% {frequency}GHz"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"
device = "BAT1"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "time"
interval = 1
format = "%a %d.%m.%Y %H:%M:%S"
